# -*- coding: utf-8 -*-
"""inventori_toko.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRN44PCRwmm9L7Oo9JgAZkCYVASSafo7
"""

# =====================================
# Aplikasi Inventori Toko Sederhana
# Versi CLI tanpa penyimpanan file
# =====================================

# List untuk menyimpan data barang (sementara, tidak disimpan ke file)
inventori = []

# Fungsi: Menampilkan menu utama
def tampilkan_menu():
    print("\n=== MENU INVENTORI TOKO ===")
    print("1. Tambah Barang")
    print("2. Lihat Semua Barang")
    print("3. Cari Barang")
    print("4. Update Stok Barang")
    print("5. Hapus Barang")
    print("6. Keluar")

# Fungsi: Menambahkan data barang baru ke list inventori
def tambah_barang():
    kode = input("Masukkan kode barang: ").strip()
    nama = input("Masukkan nama barang: ").strip()
    try:
        stok = int(input("Masukkan jumlah stok: "))  # input stok harus angka
        barang = {"kode": kode, "nama": nama, "stok": stok}  # simpan dalam dictionary
        inventori.append(barang)  # tambahkan ke list
        print("Barang berhasil ditambahkan!")
    except ValueError:
        print("Stok harus berupa angka!")  # jika input bukan angka